WebComputerStore/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace WebComputerStore.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines
            .Where(p => p.Product.ProductId == product.ProductId)
            .FirstOrDefault();

            if (line == null)
               {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Product product) =>
        Lines.RemoveAll(l => l.Product.ProductId == product.ProductId);
        public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.Product.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

WebComputerStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebComputerStore.Data.Interfaces;
using WebComputerStore.Models;

namespace WebComputerStore.Controllers
{

    public class OrderController : Controller
    {
        private IOrder repository;
        private Cart cart;

        public OrderController(IOrder repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult Checkout() => 
             View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", 
                    new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }

    }
}

WebComputerStore/Pages/AboutUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebComputerStore.Pages
{
    public class AboutUsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebComputerStore/Pages/Cart.cshtml.cs
 using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebComputerStore.Infrastructure;
using WebComputerStore.Models;
using System.Linq;
using WebComputerStore.Data.Interfaces;

namespace WebComputerStore.Pages
{

 public class CartModel : PageModel
    {
        private IAllProducts repository;
        public CartModel(IAllProducts repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }

        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product product = repository.Products
            .FirstOrDefault(p => p.ProductId == productId);
            Cart.AddItem(product, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
            cl.Product.ProductId == productId).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }

    }
}

WebComputerStore/Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebComputerStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebComputerStore/Pages/Detailed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebComputerStore.Pages
{
    public class DetailedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebComputerStore/Pages/_CartLayout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebComputerStore.Pages.Admin
{
    public class _CartLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebComputerStore/Pages/AboutUs.cshtml
@page

<div class="container">
    <div class="row justify-content-md-center">
        <div class="mbr-white col-md-10">
            <h3 class="mbr-section-subtitle align-center mbr-light pb-3 mbr-fonts-style display-2">MEET OUR STORE</h3>

            <h5 style="color:black">
                <b>Purchase computers inexpensively at</b>  <b>Computer Store</b>
            </h5>
            <p class="mbr-text align-center pb-3 mbr-fonts-style display-5">
                <b>Computer Store</b> - Computer Inexpensive purchases have never been so easy, appliances, ordering of entertainment electronics and telecommunications has never been easier than in the online shop at <b>Computer Store</b>. Helpful tools such as product filters and purchase advice support you in your search for the article you want and turn your purchase into convenient shopping
            </p>

            <h5 style="color:black"> <b>Online shop for electronics with optimum selection and service</b></h5>
            <p>
                Since 1999,  <b>Computer Store</b> has developed from a computer dispatch company into an online specialist for technology and electronics with the promise that our company lives by: "Best selection, best service". Over 100,000 articles from the fields of electronics and technology are offered by  <b>Computer Store</b> in the online shop. In addition to the large selection,  <b>Computer Store</b> provides a comprehensive payment service with a multitude of payment options e.g. PayPal, credit card and financing (purchase by instalments, payment by instalments).
            </p>

            <h5 style="color:black" ">
                <b>The customer-friendly online shop test winner  </b>
            </h5>
            <p>
                In the online shop of  <b>Computer Store</b>, the focus is always on the customer. All services are especially tailored to customer requirements. Whether laptops, tablets, mobile phones, monitors, digital camera, hard drive, tvs, washing machines, fridges or video games - for all questions concerning the offers or your order with  <b>Computer Store</b>, the personal customer service is at hand via telephone or e-mail. This customer friendliness has been praised by Stiftung Warentest, and <b>Computer Store</b> and it became the test winner among online shops.
            </p>

            <br />
            <hr />
            <br />

                <div class="container">
                    <div class="row justify-content-center">
                        <div class="title col-12 col-lg-8">
                            <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">
                                CONTACT US
                            </h2>

                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="row justify-content-center">
                        <div class="media-container-column col-lg-8" data-form-type="formoid">
                            <div data-form-alert="" hidden="">
                                Thanks for filling out the form!
                            </div>

                            <EditForm class="mbr-form" action="https://mobirise.com/" method="post" data-form-title="Mobirise Form">
                                <input type="hidden" data-form-email="true" value="R46ImfT8lRYLhZq6vpVE63L0V35bOdmwHjgn18Tp/HdDujD3JfWe/8bm7YjE2vjZZ7JFQMRNRIinYQUh3aNa2qi1GshxArFhHAffNuiFsZiNLfMCF8KElmS7V7lbqBIL">
                                <div class="row row-sm-offset">
                                    <div class="col-md-4 multi-horizontal" data-for="name">
                                        <div class="form-group">
                                            <label class="form-control-label mbr-fonts-style display-7" for="name-form1-4">Name</label>
                                            <input type="text" class="form-control" name="name" data-form-field="Name" required="" id="name-form1-4">
                                        </div>
                                    </div>
                                    <div class="col-md-4 multi-horizontal" data-for="email">
                                        <div class="form-group">
                                            <label class="form-control-label mbr-fonts-style display-7" for="email-form1-4">Email</label>
                                            <input type="email" class="form-control" name="email" data-form-field="Email" required="" id="email-form1-4">
                                        </div>
                                    </div>
                                    <div class="col-md-4 multi-horizontal" data-for="phone">
                                        <div class="form-group">
                                            <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-4">Phone</label>
                                            <input type="tel" class="form-control" name="phone" data-form-field="Phone" id="phone-form1-4">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" data-for="message">
                                    <label class="form-control-label mbr-fonts-style display-7" for="message-form1-4">Message</label>
                                    <textarea type="text" class="form-control" name="message" rows="7" data-form-field="Message" id="message-form1-4"></textarea>
                                </div>

                                <span class="input-group-btn"><button href="" type="submit" 
                                                                      class="btn btn-md btn-outline-info display-4">SEND FORM</button></span>
                            </EditForm>
                        </div>
                    </div>
                </div>

           
        </div>
    </div>
</div>

<section class="header1 cid-qyvcqB36eR" id="header1-0" data-rv-view="761">





    <div class="container">
        <div class="row justify-content-md-center">
            <div class="mbr-white col-md-10">




            </div>
        </div>
    </div>

</section>

WebComputerStore/Pages/Cart.cshtml
@page
@model CartModel

<h2>Your cart</h2>
<table class="table table-bordered table-info">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Title </td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Product.Price).ToString("c"))
            </td>


            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="ProductId"
                           value="@line.Product.ProductId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>


        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    
    <a class="btn btn-primary" 
        asp-action="Checkout" 
        asp-controller="Order">
        Checkout
    </a>

</div>

WebComputerStore/Pages/Completed.cshtml
@page
<div class="text-center">
    <h2>Thanks!</h2>
    <p>Thanks for placing order №@OrderId</p>
    <p> We'll contact with you as soon as possible! </p>
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

WebComputerStore/Pages/Detailed.cshtml
@page

@{
    Layout = "_Layout";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>



    <h3 class="bg-info text-white text-center p-1">Details</h3>
    <table class="table table-sm table-bordered table-striped">
        <tbody>
            <tr><th>ID</th><td></td></tr>
            <tr><th>Name</th><td></td></tr>
            <tr>
                <th>Description</th>
                <td></td>
                <th></th>
                <td></td>
            </tr>
            <tr><th>Category</th><td</td></tr>
            <tr><th>Price</th><td</td></tr>
        </tbody>
    </table>

</body>
</html>

WebComputerStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Computer Store</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" />

</head>
<body>
    <div class="bg-dark text-white p-2 text-right">
        <span class="navbar-brand ml-2">COMPUTER STORE</span>
        <a class="btn btn-sm btn-primary" href="home">Home</a>

    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>